// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using To_Do_List.Server.Data;

#nullable disable

namespace To_Do_List.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("To_Do_List.Server.Models.Inter_Quadro_Users", b =>
                {
                    b.Property<int>("Fk_Id_Quadro")
                        .HasColumnType("integer");

                    b.Property<int>("Fk_Id_Users")
                        .HasColumnType("integer");

                    b.HasIndex("Fk_Id_Quadro");

                    b.HasIndex("Fk_Id_Users");

                    b.ToTable("Inter_Quadro_Users");
                });

            modelBuilder.Entity("To_Do_List.Server.Models.Inter_Tarefa_Quadro", b =>
                {
                    b.Property<int>("Fk_Id_Quadro")
                        .HasColumnType("integer");

                    b.Property<int>("Fk_Id_Tarefa")
                        .HasColumnType("integer");

                    b.HasIndex("Fk_Id_Quadro");

                    b.HasIndex("Fk_Id_Tarefa");

                    b.ToTable("Inter_Tarefa_Quadro");
                });

            modelBuilder.Entity("To_Do_List.Server.Models.Quadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo_Convite")
                        .HasColumnType("text");

                    b.Property<int>("Fk_Id_User_Dono")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Id_User_Dono");

                    b.ToTable("Quadro");
                });

            modelBuilder.Entity("To_Do_List.Server.Models.Tarefas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nota")
                        .HasColumnType("text");

                    b.Property<char>("Status")
                        .HasColumnType("character(1)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("To_Do_List.Server.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = 2,
                            Email = "admin@admin.com",
                            Nome = "Admin",
                            Senha = "123"
                        });
                });

            modelBuilder.Entity("To_Do_List.Server.Models.Inter_Quadro_Users", b =>
                {
                    b.HasOne("To_Do_List.Server.Models.Quadro", "Quadro")
                        .WithMany()
                        .HasForeignKey("Fk_Id_Quadro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("To_Do_List.Server.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("Fk_Id_Users")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quadro");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("To_Do_List.Server.Models.Inter_Tarefa_Quadro", b =>
                {
                    b.HasOne("To_Do_List.Server.Models.Quadro", "Quadro")
                        .WithMany()
                        .HasForeignKey("Fk_Id_Quadro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("To_Do_List.Server.Models.Tarefas", "Tarefas")
                        .WithMany()
                        .HasForeignKey("Fk_Id_Tarefa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quadro");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("To_Do_List.Server.Models.Quadro", b =>
                {
                    b.HasOne("To_Do_List.Server.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("Fk_Id_User_Dono")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
